/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev`/`next build`. It's
// checked in here as a stub so the repo type-checks immediately after `npm install`.
